/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projetproduits;


public class App {

    public static void main(String[] args) {

        Produit[] liste = new Produit[5];

        Produit produit1 = new Produit("produit100");
        produit1.getDenomination().modifLibelle("CP", "Crayon a papier");
        produit1.setPrix(1);

        Produit produit2 = new Produit("produit200");
        produit2.getDenomination().modifLibelle("CC", "Crayon de couleur");
        produit2.setPrix(2);

        ProduitSaisonnier produit3 = new ProduitSaisonnier("produit300");
        produit3.setPrix(3);
        produit3.getDenomination().modifLibelle("Bonnet", "Bleu");
        produit3.setRemise(1);
        produit3.setSaison(Periode.aucune);

        ProduitPerissable produit4 = new ProduitPerissable("produit400");
        produit4.setDateFab(produit4.getDateFab().minusDays(7));

        produit4.getDenomination().modifLibelle("Pomme", "Verte");
        produit4.setPrix(1);

        ProduitFugace produit5 = new ProduitFugace("produit500");
        produit5.getDenomination().modifLibelle("Huitres", "abcd");
        produit5.setPrix(5);
        produit5.setRemise(1);
        produit5.setSaison(Periode.hiver);
        
        liste[0] = produit1;
        liste[1] = produit2;

        liste[2] = produit3;
        liste[3] = produit4;
        liste[4] = produit5;

        for(Produit prod : liste){
            if(prod instanceof ProduitPerissable){
                ProduitPerissable p = (ProduitPerissable)prod;
                System.out.println(p.getDateFab());
            }
            if(prod instanceof Saison){
                System.out.println(((Saison)prod).getSaison());
            }
            System.out.println(prod.getDenomination().afficheLiebelle()+" - "+prod.getPrix()+"eur");
        }
    }
}
