/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package validation.java.view;

import validation.java.modele.DBManager;
import validation.java.modele.User;

public class App {

    public static void main(String[] args) {

        DBManager.init();

        User user = new User();
        user.setPseudo("Fabien");
        // user.setPassword("allyour");
        user.setFullName("Dede");
        user.setEmail("yopiro@hotmail.fr");
        user.createUser(user);
    }
}
